"""Primera migración

Revision ID: cf5f67f1f5cf
Revises: 
Create Date: 2025-06-08 17:55:40.492440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5f67f1f5cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('coin', sa.String(), nullable=False))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('coin')
        batch_op.drop_column('status')
        batch_op.drop_column('level')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###
